### ISSUE TITLE
Only process the first camera frame

### ISSUE THREAD

**Issue by vietanhdev** [jacano/CameraPreviewAndroid#1]
Hello @jacano !
I compiled your code and tried it in my mobile phone. However I met a problem: Only the first frame was processed.
I only can run the detector with the next frames by pressing "Back" button and opening the app again.
Could you help me?
This is the screen record of this error: https://www.youtube.com/watch?v=ryWg1RYXBuY&feature=youtu.be

**Comment by jacano** [comment]
Hi @vietanhdev 
Did VS log any exception? You could try breaking on every exception to see if there is any handled one during camera initialization: https://stackoverflow.com/a/47681894
Also, have a look at the Android logcat.

I'm unable to reproduce this issue : (

**Comment by vietanhdev** [comment]
@jacano I've looked at Android logcat and fixed it. 
See this PR: [https://github.com/jacano/CameraTF/pull/2](https://github.com/jacano/CameraTF/pull/2).

**Comment by jacano** [comment]
Nice!

Thank you so much your your PR @vietanhdev
